### ISSUE TITLE
grid dimensions

### ISSUE THREAD

**Issue by brian-rose** [rodrigo-caballero/CliMT#1]
In `grid.py`, shouldn't the dimensions for latitude and longitude be set as
`self.value['nlat'] = self.Shape3D[1]`
`self.value['nlon'] = self.Shape3D[2]`
At the moment they all get set to `self.Shape3D[0]`.

**Comment by rodrigo-caballero** [comment]
Yes, I believe you're right, this is a bug. Seems nlat and nlon are never used anywhere critical, so I've never noticed this before.

**Comment by rodrigo-caballero** [comment]
left you a comment on the github page
r.

**Comment by rodrigo-caballero** [comment]
I have fixed the bug and uploaded a corrected version of grid.py
