### ISSUE TITLE
Asselin Filter

### ISSUE THREAD

**Issue by MFJansen** [rodrigo-caballero/CliMT#2]
I think there may be some issue with the Asselin filter, at least if an external time increment is imposed. I'm not sure what exactly is going on, but it may arise from the leapfrog step and filter being called for each component consecutively? (Sorry, I'm not good at python...)

Here is an example script which illustrates the issue. The results here are significantly dependent on the Asselin filter constant - even though a steady state is reached, in which case one would hope that the latter shouldn't do anything. Moreover, the radiative cooling rate does not agree with the externally applied heating rate (which it should in steady state), and there is a pretty clear relationship between the mismatch and the Asselin filter constant (seee comments in the script).

Maybe this is just an issue of understanding what the actual "effective" model time-step is. But it seems a bit funny that the latter should depend on the Asselin filter constant.

Cheers,
Malte

```
#!/usr/bin/env python

from numpy import *
import climt

### Initialize parameters
kwargs                          = {}
kwargs['lev']           = (arange(climt.get_nlev())+1)*(1000.-0.)/climt.get_nlev() ### Set pressure levels to what was modified above
kwargs['solin']         = 100 ### Solar insolation
kwargs['afc']                   = 0.2 
kwargs['dt']                    = 60.*60. ### Timestep
kwargs['Hslab']                 = 2. 
kwargs['tau_inf']       = 2.0 ### Tau
kwargs['Ts']                    = 250. ### Surface temperature init
kwargs['T']                     = ones((climt.get_nlev()))*250. ### Temperature profile init

NSteps = int( 1000*86400./kwargs['dt'] ) ## Number of steps (1000 days)

# Prescribe vertically constant heating rate of (supposedly) 1K/day
dTa = kwargs['dt']*2.*1./86400.+0.0*kwargs['lev'] 

rad = climt.radiation(scheme = 'grey', **kwargs) ### Radiation component
ocn = climt.ocean() ### ML Ocean
fed = climt.federation(rad,ocn,**kwargs) ### Coupler

### Run model
for i in range(NSteps): 

    # This formulation appears to give an effective heating rate of 1K *(1-afc) per day
    fed.step(Inc={'T':dTa})

    # This formulation appears to give an effective heating rate of 1K *(1-2*afc) per day
    #fed.step()
    #fed['T']=fed['T']+dTa

    print 'Ts: %10.5f' % (fed['Ts']-273.15)

# Print radiative temperature tendency by level - this should be -1K per day in equilibrium     
print(fed['TdotRad'])
```

**Comment by MFJansen** [comment]
Apparently this was an error only in my (older) installation of CliMT. After updating to the current GitHub version everything works as expected. 
Notice, however, that you do need to use the "Inc" option for the time stepping (i.e. the formulation that's not commented out in the example code above), so that the tendency gets properly included in the model's time-step. Notice also that the increment needs to be that for 2 time-steps (i.e. 2_dt_ dx/dt) since the model uses a leap-frog scheme.

**Comment by rodrigo-caballero** [comment]
Malte, thanks for bringing this up. My sense at this point is that the "Inc=" mechanism works but is a bit clunky and needs better documentation; I'll work on that. 
Rodrigo
