### ISSUE TITLE
Bug in units of heating rates in CAM3 radiation driver

### ISSUE THREAD

**Issue by brian-rose** [rodrigo-caballero/CliMT#5]
The file `crm.F90` converts the output from subroutines `radcswmx` and `radclwmx` from CGS to MKS units, e.g. on line 346:

```
qrl = qrl*1.e-3
```

Two problems: 
1. I don't think this is the right conversion factor. The heating rates have dimensions energy/mass/time or (length)^2 / (time)^3. So to convert from CGS to MKS should be a factor of `1.E-4`, not `1.E-3`. 
2. The heating rates `qrl` and `qrs` are actually _already_ converted to MKS units (J/kg/s).
   See line 1041 of `radlw.F90` and line 2422 of `radsw.F90`, where the factor `1.E-4` is applied.

So in the Python module, the heating rates `swhr`, `lwhr` and `TdotRad` seem to be a factor of 1000 too small. Also the `Tinc` temperature increment for the atmosphere, same problem.

If I'm right, then the fix is very simple -- just removing the lines that apply the incorrect conversion in `crm.F90`. I did this on my master branch of the CliMT code. Can't figure out how to submit a pull request for just this change without all the other stuff I've done recently.

**Comment by rodrigo-caballero** [comment]
Brian, thanks for spotting this. You're right on both counts: the correct factor is 10e-4, and radlw.F90 already applies the conversion. 

So how did I miss this huge error? The answer is that the qrl that goes back up to python is actually in K/day. To convert from J/kg/s to K/s, you need to divide by the specific heat of air, which as it happens is almost exactly 1000 J/kg/K. So the final qrl in K/day is almost correct (though for the wrong reason) and I never noticed the bug. 

I will upload a corrected version of crm.F90 to the master branch that fixes the issue.
